services:
    db:
        image: postgres
        restart: always
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        # or set shared memory limit when deploy via swarm stack
        #volumes:
        #  - type: tmpfs
        #    target: /dev/shm
        #    tmpfs:
        #      size: 134217728 # 128*2^20 bytes = 128Mb
        environment:
            POSTGRES_PASSWORD: loo4aek4eek9jaih9aepe5IelipazooW9el7Zohvao8ecaeyaiJ2epaihaigh0zuhaghaephupe
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        ports:
            - "5432:5432"
    web:
        build: .
        restart: always
        ports:
            - "4321:4321"
        depends_on:
            - db
